name: Build and deploy react site to github pages
on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure git credentials
        uses: oleksiyrudenko/gha-git-credentials@v1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Use Node.JS
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile #yarn == yarn install

      - name: Build and deploy
        run: yarn deploy